### ISSUE TITLE
btcli root list-delegates help: implies the ability to filter by wallet, yet not an option

### ISSUE THREAD

**Issue by dougsillars** [opentensor/btcli#138]
in the docs:
 $ btcli root list_delegates --wallet-name my_wallet                                                                                                                   

but --wallet-name is not listed as an option under Options, and attempting to use it leads to the error:

No such option: --wallet-name

Expected: if the example is in the docs, it should work.  IF it does not work - remove from the docs until it does.

**Comment by thewhaleking** [comment]
Closed by #139
