### ISSUE TITLE
can't find btcli

### ISSUE THREAD

**Issue by wchyan** [opentensor/btcli#208]
I have full install bittensor, but i can't find btcli

Requirement already satisfied: bittensor-cli in /root/virtual/lib/python3.12/site-packages (8.2.0)
Requirement already satisfied: wheel in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (0.44.0)
Requirement already satisfied: async-property==0.2.2 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (0.2.2)
Requirement already satisfied: aiohttp~=3.10.2 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (3.10.5)
Requirement already satisfied: backoff~=2.2.1 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (2.2.1)
Requirement already satisfied: GitPython>=3.0.0 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (3.1.43)
Requirement already satisfied: fuzzywuzzy~=0.18.0 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (0.18.0)
Requirement already satisfied: netaddr~=1.3.0 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (1.3.0)
Requirement already satisfied: numpy>=2.0.1 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (2.0.2)
Requirement already satisfied: Jinja2 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (3.1.4)
Requirement already satisfied: pycryptodome in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (3.20.0)
Requirement already satisfied: PyYAML~=6.0.1 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (6.0.2)
Requirement already satisfied: pytest in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (8.3.3)
Requirement already satisfied: python-Levenshtein in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (0.25.1)
Requirement already satisfied: rich~=13.7 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (13.8.1)
Requirement already satisfied: scalecodec==1.2.11 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (1.2.11)
Requirement already satisfied: substrate-interface~=1.7.9 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (1.7.10)
Requirement already satisfied: typer~=0.12 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (0.12.5)
Requirement already satisfied: websockets>=12.0 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (13.1)
Requirement already satisfied: bittensor-wallet>=2.0.2 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (2.0.2)
Requirement already satisfied: bt-decode==0.2.0a0 in /root/virtual/lib/python3.12/site-packages (from bittensor-cli) (0.2.0a0)
Requirement already satisfied: toml==0.10.0 in /root/virtual/lib/python3.12/site-packages (from bt-decode==0.2.0a0->bittensor-cli) (0.10.0)
Requirement already satisfied: more-itertools in /root/virtual/lib/python3.12/site-packages (from scalecodec==1.2.11->bittensor-cli) (10.5.0)
Requirement already satisfied: base58>=2.0.1 in /root/virtual/lib/python3.12/site-packages (from scalecodec==1.2.11->bittensor-cli) (2.1.1)
Requirement already satisfied: requests>=2.24.0 in /root/virtual/lib/python3.12/site-packages (from scalecodec==1.2.11->bittensor-cli) (2.32.3)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /root/virtual/lib/python3.12/site-packages (from aiohttp~=3.10.2->bittensor-cli) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /root/virtual/lib/python3.12/site-packages (from aiohttp~=3.10.2->bittensor-cli) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /root/virtual/lib/python3.12/site-packages (from aiohttp~=3.10.2->bittensor-cli) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /root/virtual/lib/python3.12/site-packages (from aiohttp~=3.10.2->bittensor-cli) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /root/virtual/lib/python3.12/site-packages (from aiohttp~=3.10.2->bittensor-cli) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /root/virtual/lib/python3.12/site-packages (from aiohttp~=3.10.2->bittensor-cli) (1.11.1)
Requirement already satisfied: termcolor in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (2.4.0)
Requirement already satisfied: eth-utils<2.3.0 in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (2.2.2)
Requirement already satisfied: password-strength in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (0.0.3.post2)
Requirement already satisfied: cryptography~=42.0.5 in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (42.0.8)
Requirement already satisfied: ansible~=6.7 in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (6.7.0)
Requirement already satisfied: ansible-vault~=2.1 in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (2.1.0)
Requirement already satisfied: munch~=2.5.0 in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (2.5.0)
Requirement already satisfied: py-bip39-bindings==0.1.11 in /root/virtual/lib/python3.12/site-packages (from bittensor-wallet>=2.0.2->bittensor-cli) (0.1.11)
Requirement already satisfied: gitdb<5,>=4.0.1 in /root/virtual/lib/python3.12/site-packages (from GitPython>=3.0.0->bittensor-cli) (4.0.11)
Requirement already satisfied: markdown-it-py>=2.2.0 in /root/virtual/lib/python3.12/site-packages (from rich~=13.7->bittensor-cli) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /root/virtual/lib/python3.12/site-packages (from rich~=13.7->bittensor-cli) (2.18.0)
Requirement already satisfied: websocket-client<2,>=0.57.0 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (1.8.0)
Requirement already satisfied: certifi>=2019.3.9 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (2024.7.4)
Requirement already satisfied: idna<4,>=2.1.0 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (3.10)
Requirement already satisfied: xxhash<4,>=1.3.0 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (3.5.0)
Requirement already satisfied: ecdsa<1,>=0.17.0 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (0.19.0)
Requirement already satisfied: eth-keys<1,>=0.2.1 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (0.5.1)
Requirement already satisfied: PyNaCl<2,>=1.0.1 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (1.5.0)
Requirement already satisfied: py-sr25519-bindings<1,>=0.2.0 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (0.2.0)
Requirement already satisfied: py-ed25519-zebra-bindings<2,>=1.0 in /root/virtual/lib/python3.12/site-packages (from substrate-interface~=1.7.9->bittensor-cli) (1.0.1)
Requirement already satisfied: click>=8.0.0 in /root/virtual/lib/python3.12/site-packages (from typer~=0.12->bittensor-cli) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/virtual/lib/python3.12/site-packages (from typer~=0.12->bittensor-cli) (4.12.2)
Requirement already satisfied: shellingham>=1.3.0 in /root/virtual/lib/python3.12/site-packages (from typer~=0.12->bittensor-cli) (1.5.4)
Requirement already satisfied: MarkupSafe>=2.0 in /root/virtual/lib/python3.12/site-packages (from Jinja2->bittensor-cli) (2.1.5)
Requirement already satisfied: iniconfig in /root/virtual/lib/python3.12/site-packages (from pytest->bittensor-cli) (2.0.0)
Requirement already satisfied: packaging in /root/virtual/lib/python3.12/site-packages (from pytest->bittensor-cli) (24.1)
Requirement already satisfied: pluggy<2,>=1.5 in /root/virtual/lib/python3.12/site-packages (from pytest->bittensor-cli) (1.5.0)
Requirement already satisfied: Levenshtein==0.25.1 in /root/virtual/lib/python3.12/site-packages (from python-Levenshtein->bittensor-cli) (0.25.1)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.8.0 in /root/virtual/lib/python3.12/site-packages (from Levenshtein==0.25.1->python-Levenshtein->bittensor-cli) (3.9.7)
Requirement already satisfied: ansible-core~=2.13.7 in /root/virtual/lib/python3.12/site-packages (from ansible~=6.7->bittensor-wallet>=2.0.2->bittensor-cli) (2.13.13)
Requirement already satisfied: setuptools in /root/virtual/lib/python3.12/site-packages (from ansible-vault~=2.1->bittensor-wallet>=2.0.2->bittensor-cli) (70.0.0)
Requirement already satisfied: cffi>=1.12 in /root/virtual/lib/python3.12/site-packages (from cryptography~=42.0.5->bittensor-wallet>=2.0.2->bittensor-cli) (1.17.1)
Requirement already satisfied: six>=1.9.0 in /root/virtual/lib/python3.12/site-packages (from ecdsa<1,>=0.17.0->substrate-interface~=1.7.9->bittensor-cli) (1.16.0)
Requirement already satisfied: eth-typing>=3 in /root/virtual/lib/python3.12/site-packages (from eth-keys<1,>=0.2.1->substrate-interface~=1.7.9->bittensor-cli) (5.0.0)
Requirement already satisfied: eth-hash>=0.3.1 in /root/virtual/lib/python3.12/site-packages (from eth-utils<2.3.0->bittensor-wallet>=2.0.2->bittensor-cli) (0.7.0)
Requirement already satisfied: cytoolz>=0.10.1 in /root/virtual/lib/python3.12/site-packages (from eth-utils<2.3.0->bittensor-wallet>=2.0.2->bittensor-cli) (0.12.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /root/virtual/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->GitPython>=3.0.0->bittensor-cli) (5.0.1)
Requirement already satisfied: mdurl~=0.1 in /root/virtual/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich~=13.7->bittensor-cli) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/virtual/lib/python3.12/site-packages (from requests>=2.24.0->scalecodec==1.2.11->bittensor-cli) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/virtual/lib/python3.12/site-packages (from requests>=2.24.0->scalecodec==1.2.11->bittensor-cli) (2.2.3)
Requirement already satisfied: resolvelib<0.9.0,>=0.5.3 in /root/virtual/lib/python3.12/site-packages (from ansible-core~=2.13.7->ansible~=6.7->bittensor-wallet>=2.0.2->bittensor-cli) (0.8.1)
Requirement already satisfied: pycparser in /root/virtual/lib/python3.12/site-packages (from cffi>=1.12->cryptography~=42.0.5->bittensor-wallet>=2.0.2->bittensor-cli) (2.22)
Requirement already satisfied: toolz>=0.8.0 in /root/virtual/lib/python3.12/site-packages (from cytoolz>=0.10.1->eth-utils<2.3.0->bittensor-wallet>=2.0.2->bittensor-cli) (0.12.1)

**Comment by thewhaleking** [comment]
What exactly are you asking?
