### ISSUE TITLE
[feature] Add a set_children command

### ISSUE THREAD

**Issue by camfairchild** [opentensor/btcli#263]
Recently, the on-chain `set_children` rate-limit was increased. However, because this command is executed once for both remove and set children on the btcli-side, this ends up attempting 2 transactions for a user to *change* children (rather than just set xor remove). 

The `btcli` should have a new command that allows the user to set the children in one chain-call, respecting the rate limit.

**Comment by antoinepln** [comment]
A simple option could be to apply the rate limit only to set_children operations when the amount is greater than 0. That way, we could switch from one hotkey to another within a subnet once per day.

**Comment by camfairchild** [comment]
> A simple option could be to apply the rate limit only to set_children operations when the amount is greater than 0. That way, we could switch from one hotkey to another within a subnet once per day.

You only need to set your children with the new set to stay within the rate limit. There's no need to add complexity.
This would also allow people to send multiple "revokes" when we only want them to send one.

IMO, this is a client-side fix. Not a chain-side fix.

**Comment by antoinepln** [comment]
okok wasn't aware of the new 'set_children' func. This resolves that indeed.

**Comment by thewhaleking** [comment]
Is there a different extrinsic to revoke children other than `SubtensorModule.set_children`?

**Comment by thewhaleking** [comment]
This is a docs issue.
